### ISSUE TITLE
Door "closed" treated as active trigger

### ISSUE THREAD

**Issue by sambarlick** [Hankanman/Area-Occupancy-Detection#8]
### Description

Contact sensors used as door sensors when closed should be treated as active triggers. 
### Additional Information

Because Home Assistant treats open as on and closed as off this integration reports open as an active trigger and closed as not active. This should be reversed as a closed door with motion in the room suggests higher probability of occupancy over an open door with no or recent motion.

**Comment by HowserMD** [comment]
Wouldn't it be more logical to categorize doors separately rather than classifying them as Motion Sensors?

**Creating separate categories for doors and motion sensors in area occupancy detection can offer several benefits:**

**Improved Accuracy**: By categorizing doors separately, you can more accurately track entry and exit points. This helps in distinguishing between people entering or leaving a space, leading to more precise occupancy data.

**Enhanced Data Analysis**: Separate categories allow for more detailed analysis. For example, you can analyze patterns of door usage independently from general motion, providing insights into traffic flow and peak usage times.

Just a thought.

**Comment by Hankanman** [comment]
There will be a new release in the next few days, I have created more device categories I'll add one for doors, good idea :)

**Comment by sambarlick** [comment]
I agree it would be nice to have Doors as its own category but my original point of having a door closed treated as active is seperate. Even if there's an invert checkbox option that new category, just so closed doors are considered active triggers.

**Comment by Hankanman** [comment]
> I agree it would be nice to have Doors as its own category but my original point of having a door closed treated as active is seperate. Even if there's an invert checkbox option that new category, just so closed doors are considered active triggers.

Understood, ill have a think about how to implement that as a toggle or something

**Comment by sambarlick** [comment]
Thanks

**Comment by sambarlick** [comment]
Thanks for your amazing work and efforts @Hankanman
